---
# tasks file for ansible-role-ubuntu-init
- name: apt_get update
  apt: update_cache=yes
  become: True

- name: install default packages
  apt: name={{ item }} state=present
  with_items:
    - python-software-properties
    - zip
    - unzip
  become: True
