---
# tasks file for ansible-role-ubuntu-init
- name: common | apt_get update
  apt: update_cache=yes

- name: common | apt_get install python_software_properties
  apt: name=python-software-properties state=present
