---
# tasks file for ansible-role-ubuntu-init
- name: apt_get update
  apt: update_cache=yes
  become: True

- name: apt_get install python_software_properties
  apt: name=python-software-properties state=present
  become: True
